### ISSUE TITLE
Bug: TVB to NEST connection

### ISSUE THREAD

**Issue by sontheimer** [multiscale-cosim/TVB-NEST#12]
The test 
https://github.com/multiscale-cosim/TVB-NEST/blob/master/tests/test_translator_tvb_to_nest.sh
sometimes does not run properly. It sometimes fails to establish the connections.

This might be related to the creation and reading of the files with port information.
- https://github.com/multiscale-cosim/TVB-NEST/blob/master/nest_elephant_tvb/translation/test_file/test_input_tvb_to_nest.py
- https://github.com/multiscale-cosim/TVB-NEST/blob/master/nest_elephant_tvb/translation/test_file/test_receive_tvb_to_nest.py

To be investigated before the next pull request.

**Comment by w-klijn** [comment]
In one of my refactoring I added a two step approach: I would wait in a
somewhat hot loop for the creation of a lock file.
And only if that file existed the other side tried to open the file. It is
part of the version with the Fat endpoints 1-4.

**Comment by sontheimer** [comment]
I saw the loop (in the test input and out files) as well as a 'safety' sleep in the shell script.
But strangely it still fails sometimes. If I check, the file(s) are created, but for some reason they are not found.
This happens every other run or so.

snippet from the console output:
```
->  ./test_translator_tvb_to_nest.sh

file to read ./test_tvb_to_nest/translation/output/0.txt
[...] [20 times this line, i.e. checks 20 times in the hot loop] 
file to read ./test_tvb_to_nest/translation/output/0.txt
Could file not unlocked after 20 attempts, exit
file to read ./test_tvb_to_nest/translation/input/0.txt
MPI connection file available after t=0 seconds
TVB_OUTPUT : Waiting for port details
TVB_OUTPUT :wait connection: tag#0$description#kim_laptop$port#35929$ifname#127.0.0.1$: ./test_tvb_to_nest/translation/input/0.txt
TVB_OUTPUT :connect to tag#0$description#kim_laptop$port#35929$ifname#127.0.0.1$
TVB_OUTPUT :wait acceptation
```

So, the TVB output connection is made, and it stops at the first 'handshake' check:
 `TVB_OUTPUT :wait acceptation`

But the NEST input connection can't find the file even though it is created.

To be further investigated.

**Comment by sontheimer** [comment]
solved with a 'hot loop' that waits for the creation of the file. Same implementation as on the NEST to TVB side.

Works for this version, but will be changed with further integration into the Co-sim framework.
